<?php

namespace ShopBundle\Repository;

/**
 * CasterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CasterRepository extends \Doctrine\ORM\EntityRepository
{
}
