<?php

namespace ShopBundle\Repository;

/**
 * purveyorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class purveyorRepository extends \Doctrine\ORM\EntityRepository
{
}
