services:
 acme_hello.upload_listener:
        class: ShopBundle\EventListener\UploadListener
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: kernel.event_listener, event: oneup_uploader.post_persist, method: onUpload }

    shop.admin.product:
        class: ShopBundle\Admin\ProductAdmin
        arguments: [~, ShopBundle\Entity\Product, ShopBundle:ProductAdmin, '@service_container']
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Product }

    shop.admin.tag:
        class: ShopBundle\Admin\TagAdmin
        arguments: [~, ShopBundle\Entity\Tag, ShopBundle:TagAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Tag }

    shop.admin.file:
        class: ShopBundle\Admin\FileAdmin
        arguments: [~, ShopBundle\Entity\File, ShopBundle:FileAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: File }
